name: Integration tests
on:
  [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debugging
        run: |
          whoami
          ls -la
          git log -p | head -n 50
          echo "$github.base_ref"

      - name: Update the system
        run: sudo apt update -y
        

      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 podman

      - name: Integration tests
        run: ./run_tests.sh --integration
