name: Integration tests
on:
  [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debugging
        run: |
          whoami
          ls -la
          echo "GitHub Base Ref: ${{ github.base_ref }}"
          echo "GitHub Head Ref: ${{ github.head_ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
          git branch -a | head -n 10

      - name: Determine base ref
        id: determine_base_ref
        run: |
          echo "BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
          
      - name: Check if build.sh was modified
        id: check_build
        run: |
          git fetch origin ${{ env.BASE_REF }}
          BASE=$(git merge-base HEAD origin/${{ env.BASE_REF }})

          echo "BASE = $BASE"
          
          if git diff --name-only $BASE HEAD | grep -q 'src/build.sh'; then
            echo "BUILD_MODIFIED=true" >> $GITHUB_ENV
            echo "build alterado"
          else
            echo "BUILD_MODIFIED=false" >> $GITHUB_ENV
            echo "build nao alterado"
          fi

      - name: Update the system
        run: sudo apt update -y
        

      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 podman

      - name: Integration tests
        run: ./run_tests.sh --integration
