name: Integration tests
on:
  [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debugging
        run: |
          whoami
          ls -la
          echo "GitHub Base Ref: ${{ github.base_ref }}"
          echo "GitHub Head Ref: ${{ github.head_ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
          git branch -a | head -n 10
          
      - name: Check if build.sh was modified
        id: check_build
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q 'src/build.sh'; then
            echo "BUILD_MODIFIED=true" >> $GITHUB_ENV
            echo "modificado"
          else
            echo "BUILD_MODIFIED=false" >> $GITHUB_ENV
            echo "nao modificado"
          fi


      - name: Update the system
        run: sudo apt update -y
        

      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 podman

      - name: Integration tests
        run: ./run_tests.sh --integration
