name: Integration tests (workflow)
on:
  [push, pull_request]

jobs:
  initialize-repository:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

  integration-tests:
    needs: initialize-repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 3

      - name: Update the system
        run: sudo apt update -y

      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 podman
      - name: os-release
        run: |
          cat /etc/os-release
      - name: Integration tests
        run: ./run_tests.sh --integration
