name: Integration tests
on:
  [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      uses: lhotari/action-upterm@v1
      
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debugging
        run: |
          whoami
          ls -la
          echo "GitHub Base Ref: ${{ github.base_ref }}"
          echo "GitHub Head Ref: ${{ github.head_ref }}"
          echo "GitHub SHA: ${{ github.sha }}"
          git branch -a | head -n 10
          echo "GitHub Pull Request Sha: ${{ github.event.pull_request.base.sha }}"

      - name: Update the system
        run: sudo apt update -y
          
      - name: Install dependencies
        run: |
          sudo apt install -y shunit2 podman

      - name: Fetch base ref
        run: git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1

      - name: Check if src/build.sh is modified
        id: check_build_script
        run: |
          if git diff --name-only ${{ github.event.pull_request.base.sha }} $GITHUB_SHA | grep -q "src/build.sh"; then
            echo "BUILD_SCRIPT_CHANGED=true" >> $GITHUB_ENV
          else
            echo "BUILD_SCRIPT_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Conditional kernel build
        if: env.BUILD_SCRIPT_CHANGED == 'true'
        run: ./run_tests.sh test build
    
      - name: Integration tests
        run: ./run_tests.sh --integration
